"""Implement user refresh tokens table

Revision ID: ddf3cca3f83e
Revises: 947dc807a833
Create Date: 2023-11-25 22:09:00.015994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ddf3cca3f83e"
down_revision: Union[str, None] = "947dc807a833"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_refresh_tokens",
        sa.Column("token", sa.String(length=120), nullable=False),
        sa.Column("expire_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("users_refresh_tokens_user_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "token", name=op.f("users_refresh_tokens_pkey")
        ),
    )
    op.create_index(
        op.f("users_refresh_tokens_token_idx"),
        "users_refresh_tokens",
        ["token"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("users_refresh_tokens_token_idx"),
        table_name="users_refresh_tokens",
    )
    op.drop_table("users_refresh_tokens")
    # ### end Alembic commands ###
