"""Update tables

Revision ID: 429a795f21ca
Revises: c547f430e031
Create Date: 2023-11-29 18:58:30.829095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "429a795f21ca"
down_revision: Union[str, None] = "c547f430e031"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "users_logins_user_id_fkey", "users_logins", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("users_logins_user_id_fkey"),
        "users_logins",
        "users",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "users_refresh_tokens_user_id_fkey",
        "users_refresh_tokens",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("users_refresh_tokens_user_id_fkey"),
        "users_refresh_tokens",
        "users",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "users_signatures_user_id_fkey", "users_signatures", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("users_signatures_user_id_fkey"),
        "users_signatures",
        "users",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("users_signatures_user_id_fkey"),
        "users_signatures",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "users_signatures_user_id_fkey",
        "users_signatures",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("users_refresh_tokens_user_id_fkey"),
        "users_refresh_tokens",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "users_refresh_tokens_user_id_fkey",
        "users_refresh_tokens",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("users_logins_user_id_fkey"), "users_logins", type_="foreignkey"
    )
    op.create_foreign_key(
        "users_logins_user_id_fkey",
        "users_logins",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
