"""User model update

Revision ID: 8b79f3a82c40
Revises: c3c718bfc512
Create Date: 2023-11-23 22:28:19.297775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b79f3a82c40"
down_revision: Union[str, None] = "c3c718bfc512"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("users_email_idx"), "users", ["email"], unique=True)
    op.create_index(
        op.f("users_username_idx"), "users", ["username"], unique=True
    )
    op.create_unique_constraint(
        op.f("users_signatures_signature_key"),
        "users_signatures",
        ["signature"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("users_signatures_signature_key"),
        "users_signatures",
        type_="unique",
    )
    op.drop_index(op.f("users_username_idx"), table_name="users")
    op.drop_index(op.f("users_email_idx"), table_name="users")
    # ### end Alembic commands ###
